#ifndef _ACTIONTYPE_H_INCLUDED
#define _ACTIONTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enActionType {
    enACTIONTYPE_NONE = 0,
    enACTIONTYPE_UNKNOWN = 1,
    enACTIONTYPE_WAIT = 2,
    enACTIONTYPE_HIGH_ATTACK = 3,
    enACTIONTYPE_LOW_ATTACK = 4,
    enACTIONTYPE_HIGH_BLOCK = 5,
    enACTIONTYPE_LOW_BLOCK = 6,
    enACTIONTYPE_HIGH_PARRY = 7,
    enACTIONTYPE_LOW_PARRY = 8,
    enACTIONTYPE_DAMAGE = 9,
    enACTIONTYPE_HEAL = 10,
    enACTIONTYPE_REVIVE = 11,
    enACTIONTYPE_DESTRUCTION = 12
} enActionType;

#define ACTIONTYPE_MAXIMUM enACTIONTYPE_DESTRUCTION

#endif // _ACTIONTYPE_H_INCLUDED
