#ifndef _ARMOURTYPE_H_INCLUDED
#define _ARMOURTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enArmourType {
    enARMOURTYPE_NONE = 0,
    enARMOURTYPE_UNKNOWN = 1,
    enARMOURTYPE_HELM = 2,
    enARMOURTYPE_MAIL = 3,
    enARMOURTYPE_BRACERS = 4,
    enARMOURTYPE_GREAVES = 5,
    enARMOURTYPE_BOOTS = 6,
    enARMOURTYPE_SHIELD = 7,
    enARMOURTYPE_CLOAK = 8
} enArmourType;

#endif // _ARMOURTYPE_H_INCLUDED
