#ifndef _COMMANDTYPE_H_INCLUDED
#define _COMMANDTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enCommandType {
    enCOMMANDTYPE_NONE = 0,
    enCOMMANDTYPE_UNKNOWN = 1,
    enCOMMANDTYPE_ADVANCE = 2,
    enCOMMANDTYPE_RETREAT = 3,
    enCOMMANDTYPE_SPREAD = 4,
    enCOMMANDTYPE_CLOSE_IN = 5,
    enCOMMANDTYPE_ATTACK = 6,
    enCOMMANDTYPE_HEAL = 7,
    enCOMMANDTYPE_CHANGE_SPEED = 8
} enCommandType;

#endif // _COMMANDTYPE_H_INCLUDED
