#ifndef _INPUTTYPE_H_INCLUDED
#define _INPUTTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enInputType {
    enINPUTTYPE_NONE = 0,
    enINPUTTYPE_UNKNOWN = 1,
    enINPUTTYPE_LOCAL_HUMAN = 2,
    enINPUTTYPE_NETWORK_HUMAN = 3,
    enINPUTTYPE_LOCAL_CPU = 4,
    enINPUTTYPE_NETWORK_CPU = 5
} enInputType;

#endif // _INPUTTYPE_H_INCLUDED
