#ifndef _SOLDIERTYPE_H_INCLUDED
#define _SOLDIERTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enSoldierType {
    enSOLDIERTYPE_NONE = 0,
    enSOLDIERTYPE_UNKNOWN = 1,
    enSOLDIERTYPE_FOOTMAN = 2,
    enSOLDIERTYPE_PIKEMAN = 3,
    enSOLDIERTYPE_ARCHER = 4,
    enSOLDIERTYPE_CLERIC = 5,
    enSOLDIERTYPE_MAGE = 6,
    enSOLDIERTYPE_CAVALIER = 7,
    enSOLDIERTYPE_MESSENGER = 8
} enSoldierType;

#endif // _SOLDIERTYPE_H_INCLUDED
