#ifndef _TERRAINTYPE_H_INCLUDED
#define _TERRAINTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enTerrainType {
    enTERRAINTYPE_NONE = 0,
    enTERRAINTYPE_UNKNOWN = 1,
    enTERRAINTYPE_GRASS = 2,
    enTERRAINTYPE_ROCK = 3,
    enTERRAINTYPE_WATER = 4,
    enTERRAINTYPE_SAND = 5,
    enTERRAINTYPE_WOOD = 6,
    enTERRAINTYPE_PATH = 7
} enTerrainType;

#endif // _TERRAINTYPE_H_INCLUDED
