#ifndef _WEAPONTYPE_H_INCLUDED
#define _WEAPONTYPE_H_INCLUDED 0xBEBACAFE

typedef enum enWeaponType {
    enWEAPONTYPE_NONE = 0,
    enWEAPONTYPE_UNKNOWN = 1,
    enWEAPONTYPE_AXE = 2,
    enWEAPONTYPE_SWORD = 3,
    enWEAPONTYPE_BOW = 4,
    enWEAPONTYPE_KNIFE = 5,
    enWEAPONTYPE_HALBERD = 6,
    enWEAPONTYPE_CLUB = 7,
    enWEAPONTYPE_MAGIC_WAND = 8
} enWeaponType;

#endif // _WEAPONTYPE_H_INCLUDED
